name: send sdf to test
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue: test
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
