version: '3.7'
name: quix-template-clickstream
services:

  redpanda:
    container_name: redpanda
    image: docker.redpanda.com/redpandadata/redpanda:v23.2.19
    command:
      - redpanda start
      - --smp 1
      - --overprovisioned
      - --node-id 0
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      # Address the broker advertises to clients that connect to the Kafka API.
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      # Address the broker advertises to clients that connect to the HTTP Proxy.
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      # Redpanda brokers use the RPC API to communicate with each other internally.
      - --rpc-addr redpanda:33145
      - --advertise-rpc-addr redpanda:33145
      - --mode dev-container
    ports:
      - 18081:18081
      - 18082:18082
      - 19092:9092
      - 19644:9644
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -E 'Healthy:.+true' || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 5s

  console:
    container_name: redpanda-console
    image: docker.redpanda.com/redpandadata/console:v2.3.8
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:9092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
        connect:
          enabled: true
          clusters:
            - name: local-connect-cluster
              url: http://connect:8083
    ports:
      - 8080:8080
    depends_on:
      - redpanda

  redis:
    container_name: redis
    image: redis:7.2.3-alpine
    ports:
      - 6379:6379

  clickstream-producer:
    container_name: clickstream-producer
    build:
      context: "./Clickstream producer"
    env_file:
      - shared.env
    environment:
      - broker_address=redpanda:9092
      - output=click-data
      - keep_timing=1
    depends_on:
      - redpanda

  lookup-data-ingestion:
    container_name: lookup-data-ingestion
    build:
      context: "./Lookup data ingestion"
    restart: no
    env_file:
      - shared.env
    environment:
      - redis_host=redis
      - redis_port=6379
      - redis_username=
      - redis_password=
    depends_on:
      - redis

  data-enrichment:
    container_name: data-enrichment
    build:
      context: "./Data enrichment"
    env_file:
      - shared.env
    environment:
      - broker_address=redpanda:9092
      - input=click-data
      - output=enriched-click-data
      - redis_host=redis
      - redis_port=6379
      - redis_username=
      - redis_password=
    depends_on:
      - redpanda
      - redis

  clickstream-event-detection:
    container_name: clickstream-event-detection
    build:
      context: "./Clickstream event detection"
    env_file:
      - shared.env
    environment:
      - broker_address=redpanda:9092
      - input=enriched-click-data
      - window_minutes=30
      - output=special-offers
      - redis_host=redis
      - redis_port=6379
      - redis_username=
      - redis_password=
    depends_on:
      - redpanda
      - redis

  data-aggregation:
    container_name: data-aggregation
    build:
      context: "./Data aggregation"
    env_file:
      - shared.env
    environment:
      - broker_address=redpanda:9092
      - input=enriched-click-data
      - redis_host=redis
      - redis_port=6379
      - redis_username=
      - redis_password=
    depends_on:
      - redpanda
      - redis
  
  # Note that this is not able to interact because the workspace id is
  # not interpreted correctly.
  # demo-webshop-frontend:
  #   container_name: demo-webshop-frontend
  #   build:
  #     context: "./Demo webshop frontend"
  #   env_file:
  #     - shared.env
  #   environment:
  #     - bearer_token=
  #     - offers_topic=special-offers
  #     - click_topic=click-data
  #   ports:
  #     - 8084:80

  demo-real-time-dashboard:
    container_name: demo-real-time-dashboard
    build:
      context: "./Demo real-time dashboard"
    env_file:
      - shared.env
    environment:
      - redis_host=redis
      - redis_port=6379
      - redis_password=
      - redis_username=
    ports:
      - 8085:80
    depends_on:
      - redis
