name: Slack Alerts
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: enriched-click-data
    required: true
  - name: webhook_url
    inputType: FreeText
    description: The webhook url to send notifications to
    defaultValue: https://slack.com/shortcuts/Ft066WV650P3/e45e36ef5ab730f9b6f9c69e747e0712
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: quix_function.py
