name: Starter transformation 2
language: Python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: test-data
    required: false
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: test-out
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
