name: products visited last hour
language: python
variables:
  - name: input
    inputType: InputTopic
    description: This is the input topic to read data from
    defaultValue: enriched-click-data
    required: true
  - name: output
    inputType: OutputTopic
    description: This is the output topic to publish data to
    defaultValue: products-last-hour
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
